### ISSUE TITLE
Discuss Requirement

### ISSUE THREAD

**Issue by RajGodhasara** [RajGodhasara/IndianCurrency#2]
- [ ] Discuss requirement and get suggestion from developers.
- [ ] Approve idea from others.

- IDEA IS: Implement service which provides platform for buyers and sellers for Indian old currency.

**Comment by sankalp-ranade** [comment]
@RajGodhasara
Please refer the doc "roadmap"  and give feedback or commit on it.

@ every one
I have created the roadmap.txt doc according to my code-practise which would be helpful for building good quality product. PR on it if you have anything to include.

**Comment by RajGodhasara** [comment]
@sankalp-ranade Great work.! lets make roadmap related decisions tonight and start gathering workflows and use cases.

**Comment by RajGodhasara** [comment]
@sankalp-ranade I have Implemented Classified Project on OsClass and Its Quite Good. and I want to continue with them. Now I am going to deploy the same on google cloud so we can review it. i will let you know once i am ready with the deployment.
